### ISSUE TITLE
Strikebreak Wall rules

### ISSUE THREAD

**Issue by ffao** [pseudoregalia-modding/pseudoregalia-archipelago#31]
Hey, pretty cool project! I was browsing the rules file and I noticed that the rules for `The Underbelly - Strikebreak Wall` do not include the `can_strikebreak` condition. Is this intentional?

**Comment by littlemeowmeow0134** [comment]
That was an oversight, thanks for the catch! Fixed now in [0.7.1.](https://github.com/pseudoregalia-modding/pseudoregalia-archipelago/releases/tag/0.7.1)
