### ISSUE TITLE
Customizable/different collectable image?

### ISSUE THREAD

**Issue by mira-drgn** [pseudoregalia-modding/pseudoregalia-archipelago#32]
I know the current sprite for collectables is probably a placeholder and it's not exactly a top development priority, but it'd be cool to be able to substitute in custom PNGs. If that's not feasible, at least changing it to something that looks more like a video game collectable or adding in some different options would be nice. Having the same anime girl peeking eerily around every corner just isn't really to my taste, and makes it feel like a hasty WIP where the first image on hand was just chucked in.

**Comment by littlemeowmeow0134** [comment]
The collectable image will be changed when the mod is has included oufits/memento and the logic for the whole game is complete.
