### ISSUE TITLE
get_kicks doesn't check for Heliacal Power

### ISSUE THREAD

**Issue by dclaganiere** [pseudoregalia-modding/pseudoregalia-archipelago#7]
Looks like `get_kicks` checks Sun Greaves twice instead of Heliacal Power.

https://github.com/pseudoregalia-modding/pseudoregalia-archipelago/blob/e12f53ad4343f4f85065d56a778f2ce1f2de5e66/AP_Randomizer/apworld/Rules.py#L19C22-L19C22

**Comment by littlemeowmeow0134** [comment]
Fixed, thanks for spotting that.
