### ISSUE TITLE
In-game messaging doesn't handle unicode/certain glyphs as well anymore

### ISSUE THREAD

**Issue by lioncash** [pseudoregalia-modding/pseudoregalia-archipelago#9]
Prior to the chat rework, sending text like "おおおっ!” (Ohh!) or some other variants of japanese through would show up reasonably well, but now it cuts off the message entirely like so:

![Untitled](https://github.com/pseudoregalia-modding/pseudoregalia-archipelago/assets/712067/a129c482-ed20-490d-89bf-d917154c952e)

This seems to also happen with other common languages, like ones that use Cyrillic too.

**Comment by littlemeowmeow0134** [comment]
Sorry about that, should be fixed now with [Version 0.4.2.](https://github.com/pseudoregalia-modding/pseudoregalia-archipelago/releases/tag/0.4.2)

**Comment by lioncash** [comment]
Thanks! I really appreciate it
